
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Classe Carte est un JPanel composée d'ImageIcon contenant chacune un mètre carre (16x16) de la carte à afficher
 * @author Sébastien
 */

import java.awt.*;
import javax.swing.*;

public class Carte extends javax.swing.JPanel 
{

	private ImageIcon[][] carres;
	private int longueur;
	private int largeur; 
	
    public Carte() 
    {
        initComponents();
        
        longueur = 0;
        largeur = 0;
    }
	
	public ImageIcon[][] getCarres() {
		return carres;
	}


	public void setCarres(ImageIcon[][] carres) {
		this.carres = carres;
	}

	/**
	* Affiche le robot aspirateur dans la Carte
	* @param x est la coordonnées en abscisse du robot
	* @param y est la coordonnées en ordonnée du robot
	*/
	public void affichageAspirateur(int x, int y)
	{
		if(Piece.getPosition(x, y).getType().charAt(0) == 'B' ||
				Piece.getPosition(x, y).getType().charAt(0) == '0')
		{
			carres[x][y].setImage(new ImageIcon("images/paspirateur.png").getImage());
		}
		else if(Piece.getPosition(x, y).getType().charAt(0) == 'T')
		{
			carres[x][y].setImage(new ImageIcon("images/taspirateur.png").getImage());
		}
	}

	public int getLongueur() {
		return longueur;
	}


	public void setLongueur(int longueur) {
		this.longueur = longueur;
	}


	public int getLargeur() {
		return largeur;
	}


	public void setLargeur(int largeur) {
		this.largeur = largeur;
	}

	@Override
	public void paint(Graphics g)
	{
		super.paint(g);
		for(int i=0; i<largeur; i++)
		{
			for(int j=0; j<longueur; j++)
			{
				g.drawImage(carres[i][j].getImage(), i*16, j*16, this);
			}
		}
	}
	
	/**
	* Enregistre l'image de son mètre carre pour chaque position
	* @param positions est le tableau de Position à afficher dans la carte
	* @param taille est la taille de positions
	* @param longueur est la longueur de la pièce représentée par positions
	* @param largeur est la largeur de la pièce représentée par positions
	*/
	public void positionsToCarte(Position[] positions, int taille, int longueur, int largeur)
	{
		this.longueur =longueur;
		this.largeur = largeur;
		carres = new ImageIcon[largeur][longueur];
		
		for(int i=0; i< taille; i++)
		{
			if(positions[i].getType().charAt(0) == 'B')
			{
				carres[positions[i].getX()][positions[i].getY()] = new ImageIcon("images/base.png");
			}
			else if(positions[i].getType().charAt(0) == 'O')
			{
				carres[positions[i].getX()][positions[i].getY()] = new ImageIcon("images/obstacle.png");
			}
			else if(positions[i].getType().charAt(0) == 'V')
			{
				carres[positions[i].getX()][positions[i].getY()] = new ImageIcon("images/vide.png");
			}
			else if(positions[i].getType().charAt(0) == '0')
			{
				carres[positions[i].getX()][positions[i].getY()] = new ImageIcon("images/p"+positions[i].getQtePoussiere()+".png");
			}
			else if(positions[i].getType().charAt(0) == 'T')
			{
				carres[positions[i].getX()][positions[i].getY()] = new ImageIcon("images/t"+positions[i].getQtePoussiere()+".png");
			}
		}
	}
	
	
    /**
     * Creates new form Carte
     */

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
