/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package robotaspirateur;

/**
 *
 * @author Sébastien
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    // Déclarations des variables //
    Piece p1;
    // Fin //
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRobot = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextPanelTest = new javax.swing.JTextPane();
        TabbedPanePiece = new javax.swing.JTabbedPane();
        PanelPieceRobot = new javax.swing.JPanel();
        ButtonTest = new javax.swing.JToggleButton();
        PanelPiece = new javax.swing.JPanel();
        Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PanelRobot.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Robot", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        TextPanelTest.setText("Poney ?");
        jScrollPane1.setViewportView(TextPanelTest);

        javax.swing.GroupLayout PanelRobotLayout = new javax.swing.GroupLayout(PanelRobot);
        PanelRobot.setLayout(PanelRobotLayout);
        PanelRobotLayout.setHorizontalGroup(
            PanelRobotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRobotLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelRobotLayout.setVerticalGroup(
            PanelRobotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRobotLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        ButtonTest.setText("jToggleButton1");
        ButtonTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPieceRobotLayout = new javax.swing.GroupLayout(PanelPieceRobot);
        PanelPieceRobot.setLayout(PanelPieceRobotLayout);
        PanelPieceRobotLayout.setHorizontalGroup(
            PanelPieceRobotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPieceRobotLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ButtonTest)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        PanelPieceRobotLayout.setVerticalGroup(
            PanelPieceRobotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPieceRobotLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ButtonTest)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        TabbedPanePiece.addTab("tab1", PanelPieceRobot);

        javax.swing.GroupLayout PanelPieceLayout = new javax.swing.GroupLayout(PanelPiece);
        PanelPiece.setLayout(PanelPieceLayout);
        PanelPieceLayout.setHorizontalGroup(
            PanelPieceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );
        PanelPieceLayout.setVerticalGroup(
            PanelPieceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        TabbedPanePiece.addTab("tab2", PanelPiece);

        jMenu1.setText("File");
        Menu.add(jMenu1);

        jMenu2.setText("Edit");
        Menu.add(jMenu2);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelRobot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPanePiece))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPanePiece)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelRobot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        p1 = new Piece("piece.txt");      
        p1.start();
    }//GEN-LAST:event_formWindowOpened

    private void ButtonTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTestActionPerformed
        TextPanelTest.setText(p1.getDescription());
    }//GEN-LAST:event_ButtonTestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ButtonTest;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JPanel PanelPiece;
    private javax.swing.JPanel PanelPieceRobot;
    private javax.swing.JPanel PanelRobot;
    private javax.swing.JTabbedPane TabbedPanePiece;
    private javax.swing.JTextPane TextPanelTest;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
